/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVP_Pasiva.Vista;

import MVP_Pasiva.Presentador.PresentadorJugada;
import Modelo.OpcionesJugada;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class VJugadaSwing extends javax.swing.JPanel implements IVJugada{
    private JFrame frame = new JFrame("Jugada");
    private PresentadorJugada presentador;
    
    public VJugadaSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesJugadaRadioBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSelectRock = new javax.swing.JButton();
        btnSelectPaper = new javax.swing.JButton();
        btnSelectScissors = new javax.swing.JButton();
        btnSelectLizard = new javax.swing.JButton();
        btnSelectSpock = new javax.swing.JButton();
        radioBtnRock = new javax.swing.JRadioButton();
        radioBtnPaper = new javax.swing.JRadioButton();
        radioBtnScissors = new javax.swing.JRadioButton();
        radioBtnLizard = new javax.swing.JRadioButton();
        radioBtnSpock = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreJugador = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();

        btnSelectRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ROCK.png"))); // NOI18N
        btnSelectRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectRockActionPerformed(evt);
            }
        });

        btnSelectPaper.setText("PAPER");
        btnSelectPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPaperActionPerformed(evt);
            }
        });

        btnSelectScissors.setText("SCISSORS");
        btnSelectScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectScissorsActionPerformed(evt);
            }
        });

        btnSelectLizard.setText("LIZARD");
        btnSelectLizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLizardActionPerformed(evt);
            }
        });

        btnSelectSpock.setText("SPOCK");
        btnSelectSpock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSpockActionPerformed(evt);
            }
        });

        OpcionesJugadaRadioBtnGroup.add(radioBtnRock);

        OpcionesJugadaRadioBtnGroup.add(radioBtnPaper);

        OpcionesJugadaRadioBtnGroup.add(radioBtnScissors);

        OpcionesJugadaRadioBtnGroup.add(radioBtnLizard);

        OpcionesJugadaRadioBtnGroup.add(radioBtnSpock);

        jLabel3.setText("ROCK");

        jLabel4.setText("PAPER");

        jLabel5.setText("SCISSORS");

        jLabel6.setText("LIZARD");

        jLabel7.setText("SPOCK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(btnSelectRock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnRock))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radioBtnPaper)
                    .addComponent(btnSelectPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radioBtnScissors)
                    .addComponent(btnSelectScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radioBtnLizard)
                    .addComponent(btnSelectLizard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radioBtnSpock)
                    .addComponent(btnSelectSpock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSelectPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectLizard, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectSpock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectRock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioBtnRock)
                    .addComponent(radioBtnPaper)
                    .addComponent(radioBtnScissors)
                    .addComponent(radioBtnLizard)
                    .addComponent(radioBtnSpock))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HAZ TU JUGADA:");

        lblNombreJugador.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreJugador.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombreJugador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnJugar.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        btnJugar.setText("GOOOO!");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnJugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectRockActionPerformed
        this.radioBtnRock.setSelected(true);
    }//GEN-LAST:event_btnSelectRockActionPerformed

    private void btnSelectPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPaperActionPerformed
        this.radioBtnPaper.setSelected(true);
    }//GEN-LAST:event_btnSelectPaperActionPerformed

    private void btnSelectScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectScissorsActionPerformed
        this.radioBtnScissors.setSelected(true);
    }//GEN-LAST:event_btnSelectScissorsActionPerformed

    private void btnSelectLizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLizardActionPerformed
        this.radioBtnLizard.setSelected(true);
    }//GEN-LAST:event_btnSelectLizardActionPerformed

    private void btnSelectSpockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSpockActionPerformed
        this.radioBtnSpock.setSelected(true);
    }//GEN-LAST:event_btnSelectSpockActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        presentador.RegistrarJugada();
        presentador.mostrarSiguienteVista();
    }//GEN-LAST:event_btnJugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup OpcionesJugadaRadioBtnGroup;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSelectLizard;
    private javax.swing.JButton btnSelectPaper;
    private javax.swing.JButton btnSelectRock;
    private javax.swing.JButton btnSelectScissors;
    private javax.swing.JButton btnSelectSpock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JRadioButton radioBtnLizard;
    private javax.swing.JRadioButton radioBtnPaper;
    private javax.swing.JRadioButton radioBtnRock;
    private javax.swing.JRadioButton radioBtnScissors;
    private javax.swing.JRadioButton radioBtnSpock;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPresentador(PresentadorJugada p) {
        presentador=p;
    }

    @Override
    public OpcionesJugada getJugada() {
        if (this.radioBtnRock.isSelected()){
            return OpcionesJugada.ROCK;
        }
        if (this.radioBtnPaper.isSelected()){
            return OpcionesJugada.PAPER;
        }
        if (this.radioBtnScissors.isSelected()){
            return OpcionesJugada.SCISSORS;
        }
        if (this.radioBtnLizard.isSelected()){
            return OpcionesJugada.LIZARD;
        }
        if (this.radioBtnSpock.isSelected()){
            return OpcionesJugada.SPOCK;
        }
        return null;
    }

    @Override
    public void setNombreJugador(String nombre) {
        this.lblNombreJugador.setText(nombre);
    }

    @Override
    public void iniciar() {
        frame.setContentPane(this);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(625, 450);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //CARGAR DATOS
        presentador.setJugador();
        this.setImagenes();
        this.radioBtnRock.setSelected(true);
    }

    @Override
    public void cerrar() {
       frame.dispose();
    }
    
    private void setImagenes(){
        this.btnSelectRock.setText("");
        this.btnSelectRock.setIcon(new ImageIcon(getClass().getResource("/Imagenes/ROCK.png")));
        this.btnSelectPaper.setText("");
        this.btnSelectPaper.setIcon(new ImageIcon(getClass().getResource("/Imagenes/PAPER.png")));
        this.btnSelectScissors.setText("");
        this.btnSelectScissors.setIcon(new ImageIcon(getClass().getResource("/Imagenes/SCISSORS.png")));
        this.btnSelectLizard.setText("");
        this.btnSelectLizard.setIcon(new ImageIcon(getClass().getResource("/Imagenes/LIZARD.png")));
        this.btnSelectSpock.setText("");
        this.btnSelectSpock.setIcon(new ImageIcon(getClass().getResource("/Imagenes/SPOCK.png")));
    }
    
    @Override
    public String getTipoVista() {
        return "Swing";
    }
}
