package MVP_Pasiva.Vista;

import MVP_Pasiva.Presentador.PresentadorPartida;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VPartidaSwing extends javax.swing.JPanel implements IVPartida{
    private JFrame frame = new JFrame("Partida de R P S L V");
    private PresentadorPartida presentador;
    private Validacion validar = new Validacion();
    
    public VPartidaSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScores = new javax.swing.JPanel();
        lblScoreJ1 = new javax.swing.JLabel();
        lblScoreJ2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreJ1 = new javax.swing.JLabel();
        lblNombreJ2 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnGuardarPartida = new javax.swing.JButton();
        btnComenzarRonda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblPartida = new javax.swing.JLabel();
        panelGanadorPartida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreGanadorPartida = new javax.swing.JLabel();

        lblScoreJ1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblScoreJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreJ1.setText("0");

        lblScoreJ2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblScoreJ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreJ2.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-");

        lblNombreJ1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreJ1.setText("Jugador 1");

        lblNombreJ2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreJ2.setText("Jugador 2");

        javax.swing.GroupLayout panelScoresLayout = new javax.swing.GroupLayout(panelScores);
        panelScores.setLayout(panelScoresLayout);
        panelScoresLayout.setHorizontalGroup(
            panelScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelScoresLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(panelScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombreJ1)
                    .addComponent(lblScoreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombreJ2)
                    .addComponent(lblScoreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        panelScoresLayout.setVerticalGroup(
            panelScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreJ1)
                    .addComponent(lblNombreJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblScoreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScoreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        btnGuardarPartida.setText("GUARDAR PARTIDA");
        btnGuardarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPartidaActionPerformed(evt);
            }
        });

        btnComenzarRonda.setText("COMENZAR RONDA");
        btnComenzarRonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarRondaActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(btnGuardarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComenzarRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComenzarRonda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        lblPartida.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPartida.setText("PARTIDA #232312 (JvJ mode)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPartida)
                .addGap(10, 10, 10))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("GANADOR PARTIDA : ");

        lblNombreGanadorPartida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNombreGanadorPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreGanadorPartida.setText("NombreGanadorPartida");

        javax.swing.GroupLayout panelGanadorPartidaLayout = new javax.swing.GroupLayout(panelGanadorPartida);
        panelGanadorPartida.setLayout(panelGanadorPartidaLayout);
        panelGanadorPartidaLayout.setHorizontalGroup(
            panelGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGanadorPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblNombreGanadorPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGanadorPartidaLayout.setVerticalGroup(
            panelGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(lblNombreGanadorPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGanadorPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGanadorPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        presentador.salirMenu();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPartidaActionPerformed
        try{
            presentador.guardarPartida();
            JOptionPane.showMessageDialog(null,"PARTIDA GUARDADA",
                    "GUARDADO",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            System.out.println("ERROR AL GUARDAR");
        }
    }//GEN-LAST:event_btnGuardarPartidaActionPerformed

    private void btnComenzarRondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarRondaActionPerformed
        presentador.iniciarRonda();
    }//GEN-LAST:event_btnComenzarRondaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzarRonda;
    private javax.swing.JButton btnGuardarPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNombreGanadorPartida;
    private javax.swing.JLabel lblNombreJ1;
    private javax.swing.JLabel lblNombreJ2;
    private javax.swing.JLabel lblPartida;
    private javax.swing.JLabel lblScoreJ1;
    private javax.swing.JLabel lblScoreJ2;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelGanadorPartida;
    private javax.swing.JPanel panelScores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPresentador(PresentadorPartida p) {
        presentador=p;
    }

    
    @Override
    public void iniciar() {
        frame.setContentPane(this);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(625, 450);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.lblNombreGanadorPartida.setText("POR DECIDIR");
        //CARGAR DATOS
        presentador.ActualizarInformacion();
    }

    @Override
    public void cerrar() {
        frame.dispose();
    }

    @Override
    public void setSalida(int scoreJ1, int scoreJ2, String nombreGanador) {
        this.lblScoreJ1.setText(String.valueOf(scoreJ1));
        this.lblScoreJ2.setText(String.valueOf(scoreJ2));
        if (nombreGanador!=null) {
            this.lblNombreGanadorPartida.setText(nombreGanador);
            //POSTCONDICIONES DE GANADOR EXISTENTE
            btnComenzarRonda.setEnabled(false);
        }
    }

    @Override
    public void setnombreJugadores(String nombreJ1, String nombreJ2) {
        this.lblNombreJ1.setText(nombreJ1);
        this.lblNombreJ2.setText(nombreJ2);
    }

    @Override
    public void setTituloPartida(String idPartida, String Modo) {
        this.lblPartida.setText("PARTIDA #"+idPartida+" ("+Modo+" mode)");
    }

    @Override
    public String getTipoVista() {
        return "Swing";
    }

}
