package MVP_Pasiva.Vista;

import MVP_Pasiva.Presentador.PresentadorRonda;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class VRondaSwing extends javax.swing.JPanel implements IVRonda{
    private JFrame frame = new JFrame("RONDA");
    private PresentadorRonda presentador;
    
    public VRondaSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        iconOpcionJugadaJ1 = new javax.swing.JLabel();
        iconOpcionJugadaJ2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreJ1 = new javax.swing.JLabel();
        lblNombreJ2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnOkRonda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNumeroRonda = new javax.swing.JLabel();
        panelGanadorRonda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGanadorRonda = new javax.swing.JLabel();

        iconOpcionJugadaJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconOpcionJugadaJ1.setText("opJugJ1");
        iconOpcionJugadaJ1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        iconOpcionJugadaJ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconOpcionJugadaJ2.setText("opJugJ2");
        iconOpcionJugadaJ2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Mael", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VS");

        lblNombreJ1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreJ1.setText("Jugador 1");

        lblNombreJ2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreJ2.setText("Jugador 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombreJ1)
                    .addComponent(iconOpcionJugadaJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombreJ2)
                    .addComponent(iconOpcionJugadaJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconOpcionJugadaJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconOpcionJugadaJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnOkRonda.setText("OK");
        btnOkRonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkRondaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOkRonda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnOkRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblNumeroRonda.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblNumeroRonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroRonda.setText("RONDA Nº: __");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNumeroRonda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumeroRonda)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("GANADOR RONDA : ");

        lblGanadorRonda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGanadorRonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGanadorRonda.setText("NombreGanadorRonda");

        javax.swing.GroupLayout panelGanadorRondaLayout = new javax.swing.GroupLayout(panelGanadorRonda);
        panelGanadorRonda.setLayout(panelGanadorRondaLayout);
        panelGanadorRondaLayout.setHorizontalGroup(
            panelGanadorRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGanadorRondaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblGanadorRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGanadorRondaLayout.setVerticalGroup(
            panelGanadorRondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(lblGanadorRonda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGanadorRonda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGanadorRonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkRondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkRondaActionPerformed
        presentador.agregarRonda();
        presentador.mostrarVistaPartida();
    }//GEN-LAST:event_btnOkRondaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkRonda;
    private javax.swing.JLabel iconOpcionJugadaJ1;
    private javax.swing.JLabel iconOpcionJugadaJ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblGanadorRonda;
    private javax.swing.JLabel lblNombreJ1;
    private javax.swing.JLabel lblNombreJ2;
    private javax.swing.JLabel lblNumeroRonda;
    private javax.swing.JPanel panelGanadorRonda;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPresentador(PresentadorRonda p) {
        presentador = p;
    }

    @Override
    public void iniciar() {
        frame.setContentPane(this);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(625, 450);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //CARGAR DATOS
        presentador.mostrarDatos();
    }

    @Override
    public void cerrar() {
        frame.dispose();
    }

    @Override
    public void setNroRonda(int NroRonda) {
       this.lblNumeroRonda.setText("RONDA Nº: "+NroRonda);
    }

    @Override
    public void setNombreJugadores(String nombreJ1, String nombreJ2) {
        this.lblNombreJ1.setText(nombreJ1);
        this.lblNombreJ2.setText(nombreJ2);
    }

    @Override
    public void setJugadas(String OpJugadaJ1, String OpJugadaJ2) {
        this.iconOpcionJugadaJ1.setText("");
        this.iconOpcionJugadaJ1.setIcon(new ImageIcon(getClass().getResource("/Imagenes/"+OpJugadaJ1+".png")));
        this.iconOpcionJugadaJ2.setText("");
        this.iconOpcionJugadaJ2.setIcon(new ImageIcon(getClass().getResource("/Imagenes/"+OpJugadaJ2+".png")));
        
    }

    @Override
    public void setSalida(String nombreGanador) {
        this.lblGanadorRonda.setText(nombreGanador);
    }
    
    @Override
    public String getTipoVista() {
        return "Swing";
    }
}
